# These settings are synced to GitHub by https://probot.github.io/apps/settings/.
repository:
  topics: lagom, distributed-systems, akka, play, playframework, java, scala, microservices, reactive
  private: false
  has_issues: true
  # Lagom already has some projects, so keeping them here
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: master
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false

teams:
  - name: write-bots
    permission: admin
  - name: integrators
    permission: admin

branches:
  - name: "*"
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      # Require status checks to pass before merging
      required_status_checks:
        # The list of status checks to require in order to merge into this branch
        contexts: ["Travis CI - Pull Request", "typesafe-cla-validator"]

labels:
  - color: f9d0c4
    name: "closed:declined"
  - color: f9d0c4
    name: "closed:duplicated"
  - color: f9d0c4
    name: "closed:invalid"
  - color: f9d0c4
    name: "closed:question"
  - color: f9d0c4
    name: "closed:wontfix"
  - color: 7057ff
    name: "good first issue"
  - color: 7057ff
    name: "Hacktoberfest"
  - color: 7057ff
    name: "help wanted"
  - color: cceecc
    name: "status:backlog"
    oldname: backlog
  - color: b60205
    name: "status:block-merge"
  - color: b60205
    name: "status:blocked"
  - color: 0e8a16
    name: "status:in-progress"
    oldname: in progress
  - color: 0e8a16
    name: "status:merge-when-green"
  - color: fbca04
    name: "status:needs-backport-1.4"
  - color: fbca04
    name: "status:needs-backport"
  - color: fbca04
    name: "status:needs-forwardport"
  - color: fbca04
    name: "status:needs-info"
  - color: fbca04
    name: "status:needs-verification"
  - color: 0e8a16
    name: "status:ready"
    oldname: ready
  - color: fbca04
    name: "status:to-review"
    oldname: review
  - color: c5def5
    name: "topic:build/tests"
  - color: c5def5
    name: "topic:dev-environment"
    oldname: "topic:development-environment"
  - color: c5def5
    name: "topic:documentation"
  - color: c5def5
    name: "topic:jdk-next"
  - color: c5def5
    name: "topic:java-api"
  - color: c5def5
    name: "topic:scala-api"
  - color: c5def5
    name: "topic:core-framework"
  - color: c5def5
    name: "topic:grpc"
  - color: c5def5
    name: "topic:message-broker-api"
  - color: c5def5
    name: "topic:persistence-api"
  - color: c5def5
    name: "topic:service-api"
  - color: c5def5
    name: "topic:service-client"
  - color: c5def5
    name: "topic:testkit"
  - color: b60205
    name: "type:defect"
  - color: 0052cc
    name: "type:feature"
  - color: 0052cc
    name: "type:improvement"
  - color: 0052cc
    name: "type:updates"
  - color: 0052cc
    name: "type:upstream"
