language: scala
dist: trusty
sudo: required
group: edge
jdk:
  - oraclejdk8
env:
  global:
    # the following `secure` is WHITESOURCE_PASSWORD which is the same for all branches.
    - secure: "A4xDS51pB8ERJPR/a5Lui//E//1L9pJ9Eg1kcRm/OR2izg7rx7p8Wemfp9gRhz8trn1mIrXDSMSK9iwENsfIP1bc/6AgtTWKBPm9DKjG0HW3swFFMBzzd6gxmOi4JD8rOtVc62Cf4qnURz+hsPRcI5C8aAW1fNi/5x1Q3HcAMtxE8EdPR7tU6Ve8utieOFPpqNQMktcL1aFusu+QddO14ZpQ944uAg0YdRRYFMG9SCbTkNDLt66AHTF4rKyZfkbM1tadqvvDez7Uo2eGK+KoQxTyrjct8W4Gqh+obOTyj1ngaPZEKvgbIJowFCrBzY5W+oNl6S+qa6PyAwq1MWKFqyUZt4P9fk3N9MDOYvuaS+YJCQd3VS4qCL9MEWahXNc3ZT+m8u5HT5axuPy+2qiKL/wrGzAXd74K9gNKuZJD7s+79Pwn34ZEbNMZ13AxyF6QkavU+Xcr5tQNwwZ+8P+k5OGoVsJOqZ3J7M+igGDRZh0fD693Wdp+mfORQqIvJFKED4daJYgTLufwt4tBLUxPUvlUZOWZFPn8DSQqTE7vsE9VPdpKSXTv1MyHxeMTiAX+XPabEWoazB8/4rljkC/EPxAButPD+AtUatfa6fIXpyGxHIvX8CFa2UnOQe9YbTRnxqa8TYvyMsWNQn1Q1eQMkvXCetqoefW5hA0UHTU5Zy4="
  matrix:
    # - SCRIPT=test-2.11
    # - SCRIPT=test-2.12
    - SCRIPT=test-sbt-0.13
    # - SCRIPT=test-sbt-1.0
    - SCRIPT="test-sbt-1.0-singleTest cassandra-overrides-default-configs"
    - SCRIPT="test-sbt-1.0-singleTest custom-port-range-for-services"
    - SCRIPT="test-sbt-1.0-singleTest distribution"
    - SCRIPT="test-sbt-1.0-singleTest external-project-javadsl"
    - SCRIPT="test-sbt-1.0-singleTest external-project-scaladsl"
    - SCRIPT="test-sbt-1.0-singleTest http-backend-switch"
    - SCRIPT="test-sbt-1.0-singleTest injected-configs"
    - SCRIPT="test-sbt-1.0-singleTest run"
    - SCRIPT="test-sbt-1.0-singleTest run-all-javadsl"
    - SCRIPT="test-sbt-1.0-singleTest run-all-scaladsl"
    - SCRIPT="test-sbt-1.0-singleTest run-play-on-conf"
    - SCRIPT="test-sbt-1.0-singleTest run-services"
    - SCRIPT="test-sbt-1.0-singleTest services-intra-communication"
    # - SCRIPT=test-maven
    # - SCRIPT=test-documentation
    # - SCRIPT=test-code-style
# important to use eval, otherwise "&&" is passed as an argument to sbt rather than being processed by bash
script: bin/$SCRIPT
before_install:
    # See https://github.com/travis-ci/travis-ci/issues/4629#issuecomment-239493916
    - rm ~/.m2/settings.xml
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala*
    - $HOME/.m2/repository
before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/com.lightbend.lagom/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.lightbend.lagom/*
  - rm -r $HOME/.m2/repository/com/lightbend/lagom/*
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
notifications:
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/773aba95141768c32dae
    on_success: always
    on_failure: always
