language: scala

# Only build PRs and tags: https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
if: type = pull_request OR tag IS present

env:
  global:
    # the following `secure` is WHITESOURCE_PASSWORD which is the same for all branches.
    - secure: "A4xDS51pB8ERJPR/a5Lui//E//1L9pJ9Eg1kcRm/OR2izg7rx7p8Wemfp9gRhz8trn1mIrXDSMSK9iwENsfIP1bc/6AgtTWKBPm9DKjG0HW3swFFMBzzd6gxmOi4JD8rOtVc62Cf4qnURz+hsPRcI5C8aAW1fNi/5x1Q3HcAMtxE8EdPR7tU6Ve8utieOFPpqNQMktcL1aFusu+QddO14ZpQ944uAg0YdRRYFMG9SCbTkNDLt66AHTF4rKyZfkbM1tadqvvDez7Uo2eGK+KoQxTyrjct8W4Gqh+obOTyj1ngaPZEKvgbIJowFCrBzY5W+oNl6S+qa6PyAwq1MWKFqyUZt4P9fk3N9MDOYvuaS+YJCQd3VS4qCL9MEWahXNc3ZT+m8u5HT5axuPy+2qiKL/wrGzAXd74K9gNKuZJD7s+79Pwn34ZEbNMZ13AxyF6QkavU+Xcr5tQNwwZ+8P+k5OGoVsJOqZ3J7M+igGDRZh0fD693Wdp+mfORQqIvJFKED4daJYgTLufwt4tBLUxPUvlUZOWZFPn8DSQqTE7vsE9VPdpKSXTv1MyHxeMTiAX+XPabEWoazB8/4rljkC/EPxAButPD+AtUatfa6fIXpyGxHIvX8CFa2UnOQe9YbTRnxqa8TYvyMsWNQn1Q1eQMkvXCetqoefW5hA0UHTU5Zy4="
  matrix:
    - TRAVIS_JDK=adopt@1.8.192-12

stages:
  - validations-and-test
  - test-build-tools
  - java-11

jobs:
  include:
    - stage: validations-and-test
      script: bin/test-code-style
      name: "Code validations (format, binary compatibilty, whitesource, etc.)"
    - script: bin/test-2.11
      name: "Run tests for Scala 2.11"
    - script: bin/test-2.12
      name: "Run tests for Scala 2.12"
    - script: bin/test-documentation
      name: "Documentation validations and tests"
    - stage: test-build-tools
      script: bin/test-sbt-0.13
      name: "Scripted tests for sbt 0.13"
    - script: bin/test-sbt-1.0
      name: "Scripted tests for sbt 1"
    - script: bin/test-maven
      name: "PublishM2 and test Maven"
    - stage: java-11
      script: bin/test-2.12
      env: TRAVIS_JDK=adopt@1.11.0-1
      name: "Run tests for Scala 2.12 and Java 11"
    - script: bin/test-sbt-1.0
      env: TRAVIS_JDK=adopt@1.11.0-1
      name: "Scripted tests for sbt 1 and Java 11"

before_install:
  # See https://github.com/travis-ci/travis-ci/issues/4629#issuecomment-239493916
  - rm ~/.m2/settings.xml
  - curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh

install:
  - $JABBA_HOME/bin/jabba install $TRAVIS_JDK
  - export JAVA_HOME="$JABBA_HOME/jdk/$TRAVIS_JDK" && export PATH="$JAVA_HOME/bin:$PATH" && java -Xmx32m -version

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.jabba/jdk
    - $HOME/.sbt
    - $HOME/.m2/repository

before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/com.lightbend.lagom/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.lightbend.lagom/*
  - rm -rf $HOME/.ivy2/local/com.lightbend.lagom/*
  - rm -rf $HOME/.ivy2/local/scala_*/sbt_*/com.lightbend.lagom/*
  - rm -r $HOME/.m2/repository/com/lightbend/lagom/*
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2aa0aeda88d31fe293d4
    on_success: change
    on_failure: always
    on_start: never
